// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  project_overview_card: dynamic(() => import("./ProjectOverviewCards")),
};
